spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    connection-timeout: 5000
    listener:
      simple:
        concurrency: 5 #并发数
        max-concurrency: 10 #最大并发数
        acknowledge-mode: manual #签收模式 auto自动 manual手工
        prefetch: 1 #限流数
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /rabbit-customer
  port: 8002

